@BaseAdress = http://localhost:5275

GET {{BaseAdress}}/api/categories
Accept: application/json

###
POST {{BaseAdress}}/api/categories
Accept: application/json
Content-Type: application/json
{
    "name": "Raflar"
}
###